export interface SeguimientoGestionContenido {
  etapa: string;
  actividad: string;
  gestion: string;
  significado: string;
  situacion: string;
  requiereAccion: boolean;
  proximoPaso: string;
}

export const SEGUIMIENTO_VERBATIMS: SeguimientoGestionContenido[] = [
  {
    etapa: "Investigación Fiscal y Admón. del Activo",
    actividad: "Pendiente",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está realizando las primeras gestiones de revisión de tu vehículo.",
    situacion: "Estamos realizando la investigación y diagnóstico necesarios para conocer la situación actual del vehículo y definir las gestiones requeridas.",
    requiereAccion: false,
    proximoPaso: "Inicio de las gestiones de saneamiento",
  },
  {
    etapa: "Investigación Fiscal y Admón. del Activo",
    actividad: "Novedad Hacienda Bogotá",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está gestionando la información necesaria ante la entidad correspondiente.",
    situacion: "Estamos realizando las gestiones necesarias para obtener la información requerida sobre las obligaciones del vehículo.",
    requiereAccion: false,
    proximoPaso: "Saneamiento",
  },
  {
    etapa: "Saneamiento Fiscal y/o Admón.",
    actividad: "Seguimiento Saneamiento Jurídico",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está gestionando una situación jurídica que debe resolverse antes de continuar con el trámite.",
    situacion: "El vehículo presenta una situación jurídica que requiere seguimiento ante la instancia correspondiente.",
    requiereAccion: false,
    proximoPaso: "Respuesta de la instancia jurídica",
  },
  {
    etapa: "Saneamiento Fiscal y/o Admón.",
    actividad: "Seguimiento Tutela",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está realizando seguimiento a una actuación jurídica relacionada con el trámite.",
    situacion: "Se encuentra en seguimiento una actuación jurídica necesaria para poder continuar con el proceso.",
    requiereAccion: false,
    proximoPaso: "Respuesta de la autoridad",
  },
  {
    etapa: "Saneamiento Fiscal y/o Admón.",
    actividad: "Seguimiento Desacato Tutela",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está realizando seguimiento a la actuación jurídica correspondiente.",
    situacion: "Estamos a la espera de la respuesta de la autoridad para continuar con el trámite.",
    requiereAccion: false,
    proximoPaso: "Respuesta de la autoridad",
  },
  {
    etapa: "Saneamiento Fiscal y/o Admón.",
    actividad: "Seguimiento Derecho de Petición",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está gestionando una solicitud formal ante la entidad correspondiente.",
    situacion: "La solicitud se encuentra en seguimiento y estamos a la espera de la respuesta necesaria para continuar.",
    requiereAccion: false,
    proximoPaso: "Respuesta de la entidad",
  },
  {
    etapa: "Saneamiento Fiscal y/o Admón.",
    actividad: "Saneamiento en curso",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está gestionando las obligaciones pendientes necesarias para avanzar con el traspaso.",
    situacion: "El vehículo se encuentra en proceso de saneamiento, incluyendo la gestión de los pasivos identificados.",
    requiereAccion: false,
    proximoPaso: "Saneamiento finalizado",
  },
  {
    etapa: "Saneamiento Fiscal y/o Admón.",
    actividad: "Pendiente Pago Multas Locatario",
    gestion: "👤 Gestión del Cliente",
    significado: "Para continuar con el trámite se requiere una gestión por parte del cliente.",
    situacion: "Se identificaron multas asociadas al locatario que deben ser atendidas antes de continuar con el traspaso.",
    requiereAccion: true,
    proximoPaso: "Pago o gestión de las multas",
  },
  {
    etapa: "Saneamiento Fiscal y/o Admón.",
    actividad: "Blindado",
    gestion: "👤 Gestión del Cliente",
    significado: "Se requiere información o documentación relacionada con el proceso de blindaje del vehículo.",
    situacion: "Estamos a la espera de la gestión necesaria para continuar con el trámite.",
    requiereAccion: true,
    proximoPaso: "Entrega de documentación / respuesta",
  },
  {
    etapa: "Gestión Documental Traspaso Bilateral",
    actividad: "Registro locatario",
    gestion: "🚗 Gestión de Tránsito",
    significado: "La autoridad de tránsito está gestionando el registro requerido para continuar con el trámite.",
    situacion: "Se está gestionando el registro del locatario ante la autoridad de tránsito correspondiente.",
    requiereAccion: false,
    proximoPaso: "Registro del locatario",
  },
  {
    etapa: "Gestión Documental Traspaso Bilateral",
    actividad: "Modificación Locatario Bilateral",
    gestion: "🚗 Gestión de Tránsito",
    significado: "La autoridad de tránsito está gestionando la modificación necesaria para continuar con el trámite.",
    situacion: "Se encuentra en proceso la modificación del locatario ante la autoridad competente.",
    requiereAccion: false,
    proximoPaso: "Respuesta de Tránsito",
  },
  {
    etapa: "Gestión Documental Traspaso Bilateral",
    actividad: "Saneamiento OK / pendiente traspaso Bilateral",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está preparando el trámite de traspaso una vez finalizado el saneamiento.",
    situacion: "El saneamiento del vehículo ya fue realizado y estamos preparando las actividades necesarias para el traspaso bilateral.",
    requiereAccion: false,
    proximoPaso: "Generación de documentación",
  },
  {
    etapa: "Gestión Documental Traspaso Bilateral",
    actividad: "Entrega documentos Traspaso Bilateral",
    gestion: "👤 Gestión del Cliente",
    significado: "Para continuar con el traspaso necesitamos recibir la documentación requerida.",
    situacion: "Estamos a la espera de los documentos necesarios para realizar el traspaso bilateral.",
    requiereAccion: true,
    proximoPaso: "Entrega de documentos",
  },
  {
    etapa: "Gestión Documental Traspaso Bilateral",
    actividad: "Generar Documentación Traspaso Bilateral",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está preparando la documentación necesaria para realizar el traspaso.",
    situacion: "Estamos elaborando y organizando los documentos requeridos para continuar con el proceso.",
    requiereAccion: false,
    proximoPaso: "Documentación lista",
  },
  {
    etapa: "Gestión Documental Traspaso Bilateral",
    actividad: "Autorización Cambio a Bilateral",
    gestion: "🏦 Gestión Bancolombia",
    significado: "Bancolombia está realizando la validación y autorización necesaria para continuar con el traspaso bilateral.",
    situacion: "El trámite se encuentra a la espera de la autorización correspondiente.",
    requiereAccion: false,
    proximoPaso: "Autorización recibida",
  },
  {
    etapa: "Gestión Documental Traspaso Bilateral",
    actividad: "Solicitar Contrato Leasing Bilateral",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está gestionando con Bancolombia la documentación necesaria para continuar.",
    situacion: "El contrato requerido no se encuentra disponible y estamos realizando la gestión para obtenerlo.",
    requiereAccion: false,
    proximoPaso: "Contrato recibido",
  },
  {
    etapa: "Gestión Documental Traspaso Bilateral",
    actividad: "Seguimiento entrega Contrato Leasing Bilateral",
    gestion: "🏦 Gestión Bancolombia",
    significado: "Bancolombia está gestionando la entrega de la documentación requerida.",
    situacion: "Estamos realizando seguimiento a la entrega del contrato necesario para continuar con el trámite.",
    requiereAccion: false,
    proximoPaso: "Contrato recibido",
  },
  {
    etapa: "Gestión Documental Traspaso Unilateral",
    actividad: "Modificación Locatario Unilateral",
    gestion: "🚗 Gestión de Tránsito",
    significado: "La autoridad de tránsito está gestionando la modificación necesaria para continuar con el trámite.",
    situacion: "Se encuentra en proceso la modificación del locatario ante la autoridad correspondiente.",
    requiereAccion: false,
    proximoPaso: "Respuesta de Tránsito",
  },
  {
    etapa: "Gestión Documental Traspaso Unilateral",
    actividad: "Saneamiento OK / pendiente traspaso Unilateral",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está preparando el trámite de traspaso una vez finalizado el saneamiento.",
    situacion: "El saneamiento ya fue realizado y estamos preparando las actividades necesarias para iniciar el traspaso unilateral.",
    requiereAccion: false,
    proximoPaso: "Generación de documentación",
  },
  {
    etapa: "Gestión Documental Traspaso Unilateral",
    actividad: "Registro locatario / Traspaso unilateral",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está gestionando el traspaso una vez recibida la respuesta requerida.",
    situacion: "Recibida la respuesta favorable sobre el registro del locatario, estamos preparando el traspaso unilateral.",
    requiereAccion: false,
    proximoPaso: "Documentación de traspaso",
  },
  {
    etapa: "Gestión Documental Traspaso Unilateral",
    actividad: "Generar Documentación Traspaso Unilateral",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está preparando la documentación necesaria para el traspaso.",
    situacion: "Estamos elaborando y organizando los documentos requeridos para continuar con el trámite.",
    requiereAccion: false,
    proximoPaso: "Envío de documentos",
  },
  {
    etapa: "Gestión Documental Traspaso Unilateral",
    actividad: "Solicitar Contrato Leasing Unilateral",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está gestionando la documentación necesaria con Bancolombia.",
    situacion: "El contrato requerido no se encuentra disponible y estamos realizando la gestión para obtenerlo.",
    requiereAccion: false,
    proximoPaso: "Contrato recibido",
  },
  {
    etapa: "Gestión Documental Traspaso Unilateral",
    actividad: "Seguimiento entrega Contrato Leasing Unilateral",
    gestion: "🏦 Gestión Bancolombia",
    significado: "Bancolombia está gestionando la entrega de la documentación requerida.",
    situacion: "Estamos realizando seguimiento a la entrega del contrato necesario para continuar.",
    requiereAccion: false,
    proximoPaso: "Contrato recibido",
  },
  {
    etapa: "Gestión Traspaso Unilateral",
    actividad: "Envío documentos Unilateral a corresponsal",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está coordinando el envío de la documentación necesaria para el trámite.",
    situacion: "La documentación requerida está disponible y estamos coordinando su envío al corresponsal.",
    requiereAccion: false,
    proximoPaso: "Documentos recibidos por corresponsal",
  },
  {
    etapa: "Gestión Traspaso Unilateral",
    actividad: "Traspaso Unilateral por Radicar",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está preparando la radicación del traspaso ante Tránsito.",
    situacion: "La documentación se encuentra lista para realizar la radicación del traspaso.",
    requiereAccion: false,
    proximoPaso: "Traspaso radicado",
  },
  {
    etapa: "Gestión Traspaso Unilateral",
    actividad: "Traspaso Unilateral en curso",
    gestion: "🚗 Gestión de Tránsito",
    significado: "La autoridad de tránsito está gestionando la solicitud de traspaso.",
    situacion: "El traspaso ya fue radicado ante Tránsito y se encuentra en proceso de revisión y aprobación.",
    requiereAccion: false,
    proximoPaso: "Aprobación del traspaso",
  },
  {
    etapa: "Gestión Traspaso Unilateral",
    actividad: "Traspaso unilateral con Boletín de rechazo / Subsanación",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está gestionando la corrección necesaria para continuar con el trámite.",
    situacion: "El trámite presentó una novedad durante la radicación y estamos trabajando en su subsanación.",
    requiereAccion: false,
    proximoPaso: "Nueva radicación",
  },
  {
    etapa: "Gestión Traspaso Bilateral",
    actividad: "Envío documentos Bilateral a corresponsal",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está coordinando el envío de la documentación necesaria.",
    situacion: "La documentación requerida está disponible y estamos coordinando su envío al corresponsal.",
    requiereAccion: false,
    proximoPaso: "Documentos recibidos",
  },
  {
    etapa: "Gestión Traspaso Bilateral",
    actividad: "Traspaso Bilateral por Radicar",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está preparando la radicación del traspaso.",
    situacion: "La documentación se encuentra lista para realizar la radicación ante Tránsito.",
    requiereAccion: false,
    proximoPaso: "Traspaso radicado",
  },
  {
    etapa: "Gestión Traspaso Bilateral",
    actividad: "Traspaso Bilateral en curso",
    gestion: "🚗 Gestión de Tránsito",
    significado: "La autoridad de tránsito está gestionando la solicitud de traspaso.",
    situacion: "El traspaso bilateral ya fue radicado y se encuentra en proceso de revisión y aprobación.",
    requiereAccion: false,
    proximoPaso: "Aprobación del traspaso",
  },
  {
    etapa: "Gestión Traspaso Bilateral",
    actividad: "Traspaso Bilateral con Boletín de rechazo / Subsanación",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está gestionando la corrección necesaria para continuar con el trámite.",
    situacion: "El trámite presentó una novedad durante la radicación y estamos trabajando en su subsanación.",
    requiereAccion: false,
    proximoPaso: "Nueva radicación",
  },
  {
    etapa: "Caso Finalizado",
    actividad: "Traspaso unilateral OK",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está realizando las actividades finales del proceso.",
    situacion: "El traspaso unilateral ya fue realizado y estamos gestionando las actividades relacionadas con la entrega de la tarjeta de propiedad.",
    requiereAccion: false,
    proximoPaso: "Entrega de tarjeta de propiedad",
  },
  {
    etapa: "Caso Finalizado",
    actividad: "Traspaso Bilateral OK",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está realizando las actividades finales del proceso.",
    situacion: "El traspaso bilateral ya fue realizado y estamos gestionando las actividades relacionadas con la entrega de la tarjeta de propiedad.",
    requiereAccion: false,
    proximoPaso: "Entrega de tarjeta de propiedad",
  },
  {
    etapa: "Caso Finalizado",
    actividad: "Tarjeta de propiedad enviada",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está gestionando la entrega de la tarjeta de propiedad.",
    situacion: "La tarjeta de propiedad fue remitida y estamos realizando seguimiento a su entrega.",
    requiereAccion: false,
    proximoPaso: "Confirmación de entrega",
  },
  {
    etapa: "Caso Finalizado",
    actividad: "Tarjeta de propiedad Entregada",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo ha completado las actividades correspondientes a la entrega del documento.",
    situacion: "La tarjeta de propiedad fue entregada y el proceso se encuentra finalizado.",
    requiereAccion: false,
    proximoPaso: "Trámite finalizado",
  },
  {
    etapa: "Caso Finalizado",
    actividad: "TP Pendiente por Enviar con Dirección",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está coordinando el envío de la tarjeta de propiedad.",
    situacion: "Contamos con la dirección de entrega y estamos programando el envío de la tarjeta.",
    requiereAccion: false,
    proximoPaso: "Envío de tarjeta",
  },
  {
    etapa: "Caso Finalizado",
    actividad: "TP Pendiente por Enviar Sin Dirección",
    gestion: "👤 Gestión del Cliente",
    significado: "Necesitamos información del cliente para poder realizar la entrega de la tarjeta.",
    situacion: "Estamos a la espera de los datos necesarios para programar el envío de la tarjeta de propiedad.",
    requiereAccion: true,
    proximoPaso: "Envío de datos de entrega",
  },
  {
    etapa: "Caso Finalizado",
    actividad: "TP Pendiente por Enviar escaladas con el Banco",
    gestion: "🏦 Gestión Bancolombia",
    significado: "Bancolombia está apoyando la gestión para obtener los datos necesarios del cliente.",
    situacion: "Estamos realizando seguimiento con Bancolombia para obtener la información requerida para la entrega de la tarjeta.",
    requiereAccion: false,
    proximoPaso: "Datos de entrega",
  },
  {
    etapa: "Caso Finalizado",
    actividad: "Traspaso realizado por Locatario",
    gestion: "👤 Gestión del Cliente",
    significado: "El trámite de traspaso fue realizado directamente por el locatario.",
    situacion: "Al verificar la información disponible, se identificó que el locatario ya realizó el traspaso del vehículo.",
    requiereAccion: false,
    proximoPaso: "Cierre del caso",
  },
  {
    etapa: "Caso Finalizado",
    actividad: "Vehículo facturado",
    gestion: "👨‍💼 Gestión Gómez Pineda",
    significado: "Nuestro equipo está completando las actividades administrativas asociadas al servicio.",
    situacion: "El servicio de traspaso ya fue gestionado y se ha generado la facturación correspondiente.",
    requiereAccion: false,
    proximoPaso: "Cierre del caso",
  },
  {
    etapa: "Caso Desistido",
    actividad: "Caso desistido",
    gestion: "🏦 Gestión Bancolombia",
    significado: "El trámite fue cerrado de acuerdo con la instrucción recibida.",
    situacion: "El caso fue desistido y no continuará con las actividades de traspaso.",
    requiereAccion: false,
    proximoPaso: "Caso cerrado",
  },
  {
    etapa: "Caso Finalizado",
    actividad: "Finalizado por instrucción de Banco sin traspaso",
    gestion: "🏦 Gestión Bancolombia",
    significado: "Bancolombia indicó el cierre del trámite sin realizar el traspaso.",
    situacion: "El caso fue cerrado por instrucción de Bancolombia y no se realizó el traspaso del vehículo.",
    requiereAccion: false,
    proximoPaso: "Caso cerrado",
  },
  {
    etapa: "Caso Finalizado",
    actividad: "Cliente Expidió Duplicado TP",
    gestion: "👤 Gestión del Cliente",
    significado: "El documento fue gestionado directamente por el cliente ante la autoridad correspondiente.",
    situacion: "Se verificó que el cliente obtuvo un duplicado de la tarjeta de propiedad después de realizado el traspaso.",
    requiereAccion: false,
    proximoPaso: "Cierre del caso",
  },
];
